### ISSUE TITLE
databases/docker-pgbouncer: Friction Point

### ISSUE THREAD

**Issue by janpio** [prisma/e2e-tests#137]
> Using two clients together, with and without a flag makes both tests flaky. 

How is that possible? @divyenduz

**Comment by divyenduz** [comment]
Using two clients together or them influencing each other? 

The prior, I instantiate two clients and use them in separate tests. 

The latter, that is just my observation, to validate, uncomment the commented test in this folder and run `yarn test`.

**Comment by divyenduz** [comment]
`candidate` as it is related to PgBouncer which is being looked into. We should move this forward by validating this and fix, if needed.

**Comment by divyenduz** [comment]
This is not reproducible anymore
