### ISSUE TITLE
digitalocean/pgbouncer: Not testing what it says in the README

### ISSUE THREAD

**Issue by janpio** [prisma/e2e-tests#378]
README says it is expected to fail without the flag/param, but tests check if it succeeds.

**Comment by divyenduz** [comment]
Interesting, the existing test without the `pgbouncer=true` flag passes. I also added another query while fixing https://github.com/prisma/e2e-tests/issues/514

This is probably another instance of unexpected behaviour https://github.com/prisma/e2e-tests/issues/494
