### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by janpio** [prisma/e2e-tests#415]
We have a few tests that are really flaky, especially if we (or renovate) merge PRs in parallel or quick succession:

![image](https://user-images.githubusercontent.com/183673/84176390-983f2680-aa81-11ea-9476-c6ff4d5b890a.png)

**Comment by janpio** [comment]
This just blocked a release again as they now have to pass before we can release something:

![image](https://user-images.githubusercontent.com/183673/85405718-1e1e9f80-b561-11ea-80b6-81f2f4846d36.png)

**Comment by steebchen** [comment]
@divyenduz Can you please look into the Heroku and netlify failures? I'll look into the remaining.

**Comment by steebchen** [comment]
azure windows via #502 
azure linux via #506
