### ISSUE TITLE
node and os not run for months?

### ISSUE THREAD

**Issue by janpio** [prisma/e2e-tests#48]
https://github.com/prisma/prisma2-e2e-tests/actions?query=workflow%3A%22test+node%22 and https://github.com/prisma/prisma2-e2e-tests/actions?query=workflow%3A%22test+os%22 could make you think that these have not been run for months - but they are just integrated in https://github.com/prisma/prisma2-e2e-tests/actions?query=workflow%3Atest.

Would be nice if we could clean that up somehow.

**Comment by steebchen** [comment]
As you said, it's just old actions which are irrelevant. I wouldn't know how to clean this up.

**Comment by janpio** [comment]
I am of course creating an issue here so you see if there is a way to do this.

But I googled for you:
https://stackoverflow.com/questions/57927115/anyone-know-a-way-to-delete-a-workflow-from-github-actions
https://github.community/t5/GitHub-Actions/Is-there-a-way-to-delete-or-hide-old-renamed-Workflows/td-p/32045
