### ISSUE TITLE
Heroku PgBouncer Buildpack didn't require "pgbouncer=true" in the connection string which is unexpected

### ISSUE THREAD

**Issue by divyenduz** [prisma/e2e-tests#494]
We tested Heroku's PgBouncer buildpack (https://github.com/prisma/e2e-tests/issues/469) and like other PgBouncer implementations (https://github.com/prisma/e2e-tests/tree/dev/databases) we expected to use `pgbouncer=true` for it to work properly.

However, it was not required in this case. This issue tracks figuring out why. 

Here is an isolated reproduction of this issue: https://github.com/divyendu-test/p2-heroku-pgbouncer-buildpack

PgBouncer config: https://github.com/heroku/heroku-buildpack-pgbouncer/blob/master/bin/gen-pgbouncer-conf.sh
PgBouncer buildpack docs: https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-pgbouncer

**Comment by janpio** [comment]
Next step: Open a PR for the other PgBouncer things and remove the string and see waht happens. If they are also fine, we are not testing the right thing here in general.

**Comment by divyenduz** [comment]
Here is a PR that shows other PgBouncer tests do fail when this flag is not used https://github.com/prisma/e2e-tests/pull/500

**Comment by divyenduz** [comment]
Next steps: 

1. Deploy other databases with a Heroku app to check if they work without the flag. 
2. Check the configuration of PgBouncer via PgBouncer buildpack

**Comment by divyenduz** [comment]
Update: We learned in insolation that DO, Heroku tests are also not failing as expected https://github.com/prisma/e2e-tests/pull/577

**Comment by divyenduz** [comment]
Update: Adding disconnect/reconnect like in https://github.com/prisma/e2e-tests/pull/654 makes it fail as expected too https://github.com/prisma/e2e-tests/pull/655#issuecomment-668530151

**Comment by janpio** [comment]
For people finding this a year later:

You can and should totally use Heroku's PgBouncer offering, but please make sure to add `pgbouncer=true` as an additional parameter to your connection string. Under minimal load it might also work without this, but only adding the parameter makes sure it will _always_ work as expected.

(Also: No need to disable Prisma's internal connection pool, that exists for another reason to do another job (parallel queries per request of for multiple requests). PgBouncer can not achieve that, but makes sure connections to the database are used effectively)
