### ISSUE TITLE
Handle `resolutions` in package.json

### ISSUE THREAD

**Issue by janpio** [prisma/e2e-tests#499]
The new version of Nexus Plugin Prisma (which is used together with Nexus Framework) bundles a specific version of Prisma CLI and Client, see this PR: https://github.com/prisma/e2e-tests/pull/498

That means a project does not have `@prisma/cli` and `@prisma/client` in its `package.json` any more and our update script can not work with that project.

But Nexus projects can use yarn resolutions to "overrule" that bundling:
```
"resolutions": {
  "@prisma/client": "a.b.c",
  "@prisma/sdk": "a.b.c",
}
```

So we would need to duplicate (or adapt) the following part of the update script: https://github.com/prisma/e2e-tests/blob/298cff5363619d789a435437ad9b4380c14fc2b7/.github/scripts/check-for-update.sh#L68-L94

If `resolutions` are present, update those instead of a dependency.

**Comment by jasonkuhrt** [comment]
About yarn resolutions: https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

Using the CLI to adjust them: https://yarnpkg.com/cli/set/resolution

**Comment by janpio** [comment]
Only in Yarn 2 CLI though I fear :/

**Comment by jasonkuhrt** [comment]
😢

**Comment by janpio** [comment]
Doing an old school string replacement might just be fine here.
