### ISSUE TITLE
Do not send slack failure message when a step eventually succeeds after a retry 

### ISSUE THREAD

**Issue by divyenduz** [prisma/e2e-tests#505]
After adding https://github.com/marketplace/actions/retry-step to reduce flaky tests https://github.com/prisma/e2e-tests/issues/415

We get slack messages multiple times, even for steps that eventually succeed with retry-step. 

We should make it so that the slack failure message is only sent when all retry attempts have failed.

**Comment by janpio** [comment]
I am not sure I fully agree with this. Couldn't failing individual tests point to a problem that we should be aware of and need to fix, even though retries "fix" it most of the time?

**Comment by divyenduz** [comment]
> I am not sure I fully agree with this. Couldn't failing individual tests point to a problem that we should be aware of and need to fix, even though retries "fix" it most of the time?

We should still at least try to change the symbol of an intermediate failure. Something like

Any but last retry failed :❓
The last retry failed: ❌ 

Based on the last few days of watching the feed, I think it is somewhat valuable that we know when the retry step is reducing flakiness.
