### ISSUE TITLE
Improve PgBouncer tests to make sure without `pgbouncer=true` things would actually break

### ISSUE THREAD

**Issue by janpio** [prisma/e2e-tests#514]
Right now our tests do not seem to send enough or the right queries to make sure things break without the param in the connection URL, and do not break any more with it.

**Comment by divyenduz** [comment]
They also do not break if the DB/PgBouncer state has been reset since we only send 1 query

**Comment by divyenduz** [comment]
I am still unable to make anything except docker PgBouncer fail, this PR (https://github.com/prisma/e2e-tests/pull/577) adds snapshot tests for the client call that should fail but it doesn't.
